// Geverifieerde regelingen, peildatum 7 juli 2026.
// Bedragen en deadlines wijzigen jaarlijks: behandel dit als startpunt,
// werk bij via de bronlink en zet laatstGecheckt op de echte controledatum.
const LAATST_GECHECKT = new Date("2026-07-07");

export const subsidies = [
  {
    id: "sub-jantje-beton",
    naam: "Geld voor een Speelplek",
    verstrekker: "Jantje Beton",
    niveau: "fonds",
    regio: null,
    doelgroep: "Buurtinitiatieven, scholen en organisaties met een openbare speelplek",
    maxBedrag: 10000,
    percentage: "Gemeente legt minimaal een gelijk bedrag bij",
    voorwaarden: "Meerdere aanvraagrondes per jaar; speelplek moet openbaar toegankelijk zijn.",
    deadline: null,
    doorlopend: true,
    status: "open",
    bronlink: "https://jantjebeton.nl/spelregels",
  },
  {
    id: "sub-ivn-cultuurfonds",
    naam: "IVN Natuureducatie Fonds",
    verstrekker: "Het Cultuurfonds",
    niveau: "fonds",
    regio: null,
    doelgroep: "Natuureducatieprojecten voor kinderen",
    maxBedrag: 2000,
    percentage: "Tot 75% (minimaal 25% eigen bijdrage)",
    voorwaarden: "Doorlopend aan te vragen; reken op maximaal 3 maanden doorlooptijd.",
    deadline: null,
    doorlopend: true,
    status: "open",
    bronlink: "https://www.cultuurfonds.nl",
  },
  {
    id: "sub-utrecht-vouchers",
    naam: "Vouchers groene schoolpleinen",
    verstrekker: "Provincie Utrecht",
    niveau: "provincie",
    regio: "Utrecht",
    doelgroep: "Scholen in de provincie Utrecht",
    maxBedrag: 20000,
    percentage: "15.000 euro standaard, 20.000 euro voor versteende of lage-SES-wijk; rest via stapeling",
    voorwaarden: "Aanvraagperiode 5 januari tot 30 november. Budget 2026 is bereikt; regeling heropent 4 januari 2027.",
    deadline: new Date("2026-11-30"),
    doorlopend: false,
    status: "onzeker",
    bronlink: "https://www.provincie-utrecht.nl",
  },
  {
    id: "sub-overijssel-groene-schoolpleinen",
    naam: "Groene schoolpleinen (Natuur voor Elkaar)",
    verstrekker: "Provincie Overijssel",
    niveau: "provincie",
    regio: "Overijssel",
    doelgroep: "Scholen in Overijssel",
    maxBedrag: 20000,
    percentage: "Max 50% (75% bij inzet vrijwilligersuren); 15.000 euro beplanting + 5.000 euro bomen",
    voorwaarden: "Doorlopend, op is op.",
    deadline: null,
    doorlopend: true,
    status: "open",
    bronlink: "https://regelen.overijssel.nl",
  },
  {
    id: "sub-brabant-schoolplein-toekomst",
    naam: "Schoolplein van de Toekomst",
    verstrekker: "Provincie Noord-Brabant, Cultuurfonds NB en waterschappen",
    niveau: "provincie",
    regio: "Noord-Brabant",
    doelgroep: "Scholen in Noord-Brabant",
    maxBedrag: 10000,
    percentage: "Tot 70%",
    voorwaarden: "Aanvraagperiode 1 april tot 3 november 2026.",
    deadline: new Date("2026-11-03"),
    doorlopend: false,
    status: "open",
    bronlink: "https://www.schoolpleinvandetoekomst.nl",
  },
  {
    id: "sub-jong-leren-eten",
    naam: "Stimuleringsbijdrage Lekker naar buiten!",
    verstrekker: "Jong Leren Eten (Rijk)",
    niveau: "landelijk",
    regio: null,
    doelgroep: "Scholen en kinderopvanglocaties (moestuinieren, koken, boerderij-educatie)",
    maxBedrag: 7500,
    percentage: "1.500 euro per locatie, maximaal 5 locaties",
    voorwaarden: "Ronde 9 liep van 2 maart tot 13 april 2026 en is verlopen; volgende ronde verwacht voorjaar 2027.",
    deadline: new Date("2026-04-13"),
    doorlopend: false,
    status: "open",
    bronlink: "https://www.jonglereneten.nl",
  },
  {
    id: "sub-postcodeloterij-buurtfonds",
    naam: "Buurtfonds: Vergroen je buurt",
    verstrekker: "Postcode Loterij Buurtfonds (Stichting DOEN)",
    niveau: "fonds",
    regio: null,
    doelgroep: "Buurtinitiatieven die hun omgeving vergroenen",
    maxBedrag: 5000,
    percentage: "Minimaal 500 euro, in verhouding tot de begroting",
    voorwaarden: "Hele jaar aan te vragen; campagnes lopen apart.",
    deadline: null,
    doorlopend: true,
    status: "open",
    bronlink: "https://www.postcodeloterijbuurtfonds.nl",
  },
  {
    id: "sub-zeeland-groene-revolutie",
    naam: "Groene Revolutie Schoolpleinen",
    verstrekker: "IVN, Provincie Zeeland en gemeenten",
    niveau: "provincie",
    regio: "Zeeland",
    doelgroep: "Scholen in Zeeland",
    maxBedrag: 10000,
    percentage: "Plus 5.000 euro gemeente en 5.000 euro school (cofinanciering verplicht)",
    voorwaarden: "Inschrijving in het voorjaar; circa 8 scholen per jaar.",
    deadline: null,
    doorlopend: false,
    status: "open",
    bronlink: "https://www.ivn.nl",
  },
  {
    id: "sub-rotterdam-groenblauw",
    naam: "Groenblauwe schoolpleinen",
    verstrekker: "Gemeente Rotterdam",
    niveau: "gemeente",
    regio: "Rotterdam",
    doelgroep: "Scholen in Rotterdam (nieuwbouw en bestaand)",
    maxBedrag: 80000,
    percentage: "Max 80.000 euro voor bestaande pleinen; subsidieplafond 400.000 euro",
    voorwaarden: "Jaarlijkse rondes.",
    deadline: null,
    doorlopend: false,
    status: "open",
    bronlink: "https://lokaleregelgeving.overheid.nl",
  },
  {
    id: "sub-zuid-holland-themafonds",
    naam: "Themafonds Groenblauwe Schoolpleinen Zuid-Holland",
    verstrekker: "Cultuurfonds Zuid-Holland en De Groene Motor",
    niveau: "provincie",
    regio: "Zuid-Holland",
    doelgroep: "Scholen in Zuid-Holland",
    maxBedrag: 15000,
    percentage: "1.000 tot 15.000 euro, max 50%",
    voorwaarden: "LET OP: regeling 2019-2021, vermoedelijk vervangen door de Groene Pluspuntenregeling Zuid-Holland. Verifieer voor gebruik.",
    deadline: null,
    doorlopend: false,
    status: "onzeker",
    bronlink: "https://www.cultuurfonds.nl",
  },
] as const;

export { LAATST_GECHECKT };
